type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "University Graduate Fellowship"
subtitle = "Arizona State University"
date = "Spring 2026"

[[items]]
title = "Global Security Initiative (GSI) Fellowship"
subtitle = "Arizona State University"
date = "Fall 2025"

[[items]]
title = "Finalist Prize, American Mathematical Contest in Modeling"
date = "2023"
