type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."
footer_source = "teaching_footer.md"

[[items]]
title = "CSE 220: Programming for Computer Engr"
subtitle = "Teaching Assistant"
date = "2026 Spring C"
content = "Working with Prof. Adwith Malpe."

[[items]]
title = "CSE 475: Foundation of Machine Learning"
subtitle = "Teaching Assistant"
date = "2025 Fall C"
content = "Working with Prof. Robert K. Atkinson."
