type = "card"
title = "教学"
description = "我曾参与授课或助教的课程。"

[[items]]
title = "CSE 220: Programming for Computer Engr"
subtitle = "助教"
date = "2026 Spring C"
content = "与 Adwith Malpe 教授合作。"

[[items]]
title = "CSE 475: Foundation of Machine Learning"
subtitle = "助教"
date = "2025 Fall C"
content = "与 Robert K. Atkinson 教授合作。"
