type = "card"
title = "奖项"
description = "我获得的荣誉与奖项。"

[[items]]
title = "校级研究生奖学金"
subtitle = "亚利桑那州立大学"
date = "2026 春季"

[[items]]
title = "全球安全倡议（GSI）奖学金"
subtitle = "亚利桑那州立大学"
date = "2025 秋季"

[[items]]
title = "美国大学生数学建模竞赛 Finalist Prize"
date = "2023"
